#ifndef GLOBAL_CONSTS_H
#define GLOBAL_CONSTS_H

#define SCREEN_WIDTH 1200
#define SCREEN_HEIGHT 800

#define PLAYER_WIDTH 32
#define PLAYER_HEIGHT 32

#define MAP_WIDTH (SCREEN_WIDTH)
#define MAP_HEIGHT (SCREEN_HEIGHT)

#define MIN_TILE_SIZE 128
#define TILE_SQUARE_SIDE 1
#define LVL_PATH_SIZE 32

#define P_TABLE_SIZE 256
#define PERLIN_TERRAIN_FREQ 0.015
#define PERLIN_OCTAVES 8

#endif